### PR TITLE
Remove jsonp

### LINKED ISSUE #2: jsonp
**if we use jsonp datatype we should explain what that is/means**
$.ajax({
    url: 'https://api.github.com/repos/rails/rails/stargazers',
    type: 'POST',
    dataType: 'jsonp'
  }).done(function(response) {
    var users = response.data;
    printStargazers(users);
  });

### PR DESCRIPTION
**Pull request by pletcher**
Fixes #2

The jsonp data type doesn't make sense here for a number of reasons (and the request had some issues, too), but chiefly that the README introduces a POST request _after_ this call

### CODE REVIEW

**Comment by victhevenot** [comment]
@pletcher 
I walked through this readme and copy and pasted all the appropriate code from the Readme, started the server, filled in some markdown, and it never rendered html from that markdown.

I entered `_hey_`.

**Comment by pletcher** [comment]
Got it, I'll take a look -- thanks!

**Comment by pletcher** [comment]
Hmmm, it actually works for me. Want to pair when you get a chance?

**Comment by pletcher** [comment]
Thanks! :ship:ing

**Pull request merged**
